// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_UnTFP_TB8sQcVVJMYClBe_zjcScVLE',
    appId: '1:355947127700:web:9500b9bbfaf08cf5caa581',
    messagingSenderId: '355947127700',
    projectId: 'instagram-demo-b9066',
    authDomain: 'instagram-demo-b9066.firebaseapp.com',
    storageBucket: 'instagram-demo-b9066.appspot.com',
    measurementId: 'G-MMW53MKKDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF9iVxXcacpFr0xBU-bECZ78lBbiITxtE',
    appId: '1:355947127700:android:a59f73e52bafbaeccaa581',
    messagingSenderId: '355947127700',
    projectId: 'instagram-demo-b9066',
    storageBucket: 'instagram-demo-b9066.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPSY6rgrPsUJFCLxaaaktmh02ouHzJ9cI',
    appId: '1:355947127700:ios:25c411393befb7eccaa581',
    messagingSenderId: '355947127700',
    projectId: 'instagram-demo-b9066',
    storageBucket: 'instagram-demo-b9066.appspot.com',
    iosClientId: '355947127700-pjva47g4jmfvaokabuu143b37b4vjmsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramDemo',
  );
}
